name: Test React Native App

on: [push]

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cypress run
              uses: cypress-io/github-action@v3
              with:
                project: ./cypress
                browser: firefox
                start: npm start

