name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: 4.4.4
        mongodb-replica-set: test-rs
        mongodb-port: 42069
        mongodb-db: test-db

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: node test.js
      env:
        CI: true