name: Example Workflow

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONNECTION_URI: 'balls'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Display CONNECTION_URI
        run: node test1.js
