name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: 4.4.4
        mongodb-username: supercharge
        mongodb-password: secret
        mongodb-db: supercharge
        mongodb-port: 3000

    - run: npm install

    - run: node test.js
      env:
        CI: true