name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
        mongo:
          image: "mongo:4.4.4"
          ports:
            - 27018:27017
          options: >-
            --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 12

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: 4.4.4

    - name: Add MongoDB user
      run: |
        mongo --host localhost --port 27018 --eval "db.getSiblingDB('admin').createUser({ user: 'username', pwd: 'password', roles: [{ role: 'readWrite', db: 'mydatabase' }] })"
      
    - run: npm install

    - run: npm test
      env:
        CI: true
