name: Local MongoDB Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  local-mongodb:
    runs-on: ubuntu-latest  # Adjust as needed based on the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Start mongo
        id: start-mongo
        run: docker run --rm -d -p 27017:27017 --name mongo  mongo:4.4.4 --replSet test --bind_ip_all


      - name: Setup local MongoDB instance
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '4.4'  # Specify the MongoDB version you want to use
          mongodb-db: 'mydatabase'  # Optional: specify a database name to use
          mongodb-username: 'admin'  # Specify the username for the MongoDB instance
          mongodb-password: 'adminpass'  # Specify the password for the MongoDB instance
        id: mongo-setup

      - name: Create a user in the local MongoDB instance
        run: |
          # Retrieve the MongoDB URI from the action output
          MONGODB_URI="${{ steps.mongo-setup.outputs.mongodb-uri }}"

          # Define the user details
          USERNAME="testuser"
          PASSWORD="testpassword"

          # Connect to the local MongoDB instance and create a new user
          mongo $MONGODB_URI --eval "db.createUser({
            user: '$USERNAME',
            pwd: '$PASSWORD',
            roles: [
              { role: 'readWrite', db: 'mydatabase' }
            ]
          })"

          # Output a success message if the user creation is successful
          echo "User '$USERNAME' created successfully in the local MongoDB instance."

