name: Setup MongoDB and Add User

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  setup-mongodb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MongoDB container
      run: |
        docker run -d --name mongodb-container -p 27017:27017 mongo:latest

    - name: Wait for MongoDB to be ready
      run: |
        echo "Waiting for MongoDB to start..."
        sleep 30  # Give MongoDB some time to start up

    - name: Create MongoDB user
      run: |
        mongo admin --host 127.0.0.1 --port 27017 --eval "db.createUser({user: 'username', pwd: 'password', roles: [{role: 'readWrite', db: 'mydatabase'}]})"
      
    - name: Display MongoDB users
      run: |
        mongo admin --host 127.0.0.1 --port 27017 --eval "db.getUsers()"

    - name: Clean up
      run: |
        docker stop mongodb-container
        docker rm mongodb-container
